### ISSUE TITLE
Documentation for the SL CPI manifest syntax?

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/bosh-softlayer-cpi#109]
Is there documentation anywhere for the manifest syntax required for the SL CPI?  We have not been able to find it, and thus far we've mostly had to stick to trial-and-error to figure out what works/does not work.

**Comment by jianqiu** [comment]
You should get all some documents from https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release,  we will update all these documents in the near future.
