### ISSUE TITLE
Please describe the branching and tagging policies used with this project and what branch PRs should be based on

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#112]
It appears `master` is no longer the active development branch as final releases of [cloudfoundry-incubator/bosh-softlayer-cpi-release](https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release) are being cut from commits that don't exist in that branch. This makes me wonder what branch people should create pull requests against.

It would also be great if the promotion policy (if/when something gets to master) was explicitly called out.

**Comment by cppforlife** [comment]
I would recommend taking approach other cpi releases took:

- all work happens on master (no develop or some other branch)
- releases are cut from master when necessary
- users consume releases so its ok if master breaks occasionally

**Comment by jianqiu** [comment]
I had swapped the branches, all work will happen on master, and  cloudfoundry-incubator/bosh-softlayer-cpi-release had been updated accordingly. Thanks!

**Comment by maximilien** [comment]
Yup `master` is main branch, however we do have v1 and v2 releases actively supported.
