### ISSUE TITLE
CPI should be able to convert the name of vlans to their IDs

### ISSUE THREAD

**Issue by midoblgsm** [cloudfoundry/bosh-softlayer-cpi#113]
Trying to use bosh-init to deploy director to softlayer. Only the name of vlans is accessible through Softlayer portal. So I used the names of vlans instead of their IDs. Unfortunately, the deployment failed and I needed to get the vlan IDs using softalyer API and replace it in the manifest. The CPI should be able to do that automatically.

**Comment by maximilien** [comment]
Thanks @midoblgsm for the feedback and suggestion. I opened tracker issue [#120649115](https://www.pivotaltracker.com/story/show/120649115) for this issue. Feel free to subscribe to that story to monitor progress.

**Comment by maximilien** [comment]
@mattcui and @jianqiu any updates on this. I believe this is fixed now. Correct?

**Comment by maximilien** [comment]
I believe this is now done. @midoblgsm if you have a chance confirm and if not working then re-open.
