### ISSUE TITLE
bin/test-unit fails on pristine checkout of develop_v2 and master branches

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#115]
Running `bin/test-unit` fails with the following:

```
$ bin/test-unit 
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists

 Cleaning build artifacts...

 Formatting packages...

 Integration Testing packages:
Will skip:
  ./integration
  ./integration/attach_disk
  ./integration/concurrency_sqlite
  ./integration/create_disk
  ./integration/create_stemcell
  ./integration/create_vm
  ./integration/delete_disk
  ./integration/delete_stemcell
  ./integration/delete_vm
  ./integration/detach_disk
  ./integration/has_vm
  ./integration/os_reload
  ./integration/set_vm_metadata
[1464642019] Action Suite - 79/79 specs - 7 nodes ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 42.782084ms 
[1464642019] Dispatcher Suite - 19/19 specs - 7 nodes ••••••••••••••••••• SUCCESS! 32.790795ms 
[1464642019] Transport Suite - 3/3 specs - 7 nodes ••• SUCCESS! 14.166888ms 
[1464642019] Common Suite - 2/2 specs - 7 nodes •• SUCCESS! 14.645487ms 
[1464642019] Main Suite - 5/5 specs - 7 nodes ••••• SUCCESS! 11.319801ms 
[1464642019] Baremetal Suite - 10/10 specs - 7 nodes •••••••••• SUCCESS! 25.274454ms 
[1464642019] Disk Suite - 5/5 specs - 7 nodes ••••• SUCCESS! 18.945243ms 
[1464642019] Stemcell Suite - 6/6 specs - 7 nodes •••••• SUCCESS! 1.026575137s 
[1464642019] VM Suite - 61/61 specs - 7 nodes ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 2.018823643s 
[1464642019] Pool Suite - 3/3 specs - 7 nodes ••• SUCCESS! 18.063447ms 
[1464642019] TestHelpers Suite - 6/6 specs - 7 nodes •••••
------------------------------
• Failure [0.002 seconds]
helper functions for integration tests #RunCpi [It] /out/cpi to exist and run 
/Users/sykesm/workspace/bosh-softlayer-cpi-release/src/github.com/cloudfoundry/bosh-softlayer-cpi/test_helpers/integration_helpers_test.go:55

  Expected error:
      <*os.PathError | 0xc8201e8900>: {
          Op: "fork/exec",
          Path: "/Users/sykesm/workspace/bosh-softlayer-cpi-release/src/github.com/cloudfoundry/bosh-softlayer-cpi/out/cpi",
          Err: 0x2,
      }
      fork/exec /Users/sykesm/workspace/bosh-softlayer-cpi-release/src/github.com/cloudfoundry/bosh-softlayer-cpi/out/cpi: no such file or directory
  not to have occurred

  /Users/sykesm/workspace/bosh-softlayer-cpi-release/src/github.com/cloudfoundry/bosh-softlayer-cpi/test_helpers/integration_helpers_test.go:54
------------------------------


Summarizing 1 Failure:

[Fail] helper functions for integration tests #RunCpi [It] /out/cpi to exist and run 
/Users/sykesm/workspace/bosh-softlayer-cpi-release/src/github.com/cloudfoundry/bosh-softlayer-cpi/test_helpers/integration_helpers_test.go:54

Ran 6 of 6 Specs in 0.021 seconds
FAIL! -- 5 Passed | 1 Failed | 0 Pending | 0 Skipped 

Ginkgo ran 11 suites in 1m2.094040482s
Test Suite Failed

SUITE FAILURE
```

Perhaps the test_helpers package should not be part of the unit tests? Or is it that the cpi should be built before attempting to execute? Or is it that the before suite for the helper test should be building the binary?

**Comment by mattcui** [comment]
I modified the test_unit script to add one line code to make a build prior to TestHelpers test. Thanks for pointing to this issue. 

commit -> https://github.com/cloudfoundry/bosh-softlayer-cpi/commit/c0db0f60873cb5f673324505211d87e37c9be403

**Comment by jianqiu** [comment]
From now,  all work should happen on master as other cpi releases took the same approach.

**Comment by sykesm** [comment]
You should consider using the [gexec.Build](https://godoc.org/github.com/onsi/gomega/gexec#Build) pattern in the test code. That will ensure the build is up to date without relying on scripts.

You can find lots of examples in the [diego](https://github.com/cloudfoundry-incubator/file-server/blob/ca1402a2bc667e5443be43cbbcb0020023e7b47d/cmd/file-server/main_suite_test.go#L22) code.

**Comment by mattcui** [comment]
@sykesm, Thanks for your suggestion. Seems there can't specify output binary path/name in [gexec.BuildIn](https://github.com/onsi/gomega/blob/master/gexec/build.go#L39), but there hardcoded "out/cpi" in our code, so it's not easy to use this pattern in the current situation, we will consider it later. Thanks.

**Comment by mattcui** [comment]
@sykesm, Thanks for your suggestion. Seems there can't specify output binary path/name in [gexec.BuildIn](https://github.com/onsi/gomega/blob/master/gexec/build.go#L39), but there hardcoded "out/cpi" in our code, so it's not easy to use this pattern in the current situation, we will consider it later. Thanks.

**Comment by mattcui** [comment]
@sykesm, Thanks for your suggestion. Seems there can't specify output binary path/name in [gexec.BuildIn](https://github.com/onsi/gomega/blob/master/gexec/build.go#L39), but there hardcoded "out/cpi" in our code, so it's not easy to use this pattern in the current situation, we will consider it later. Thanks.

**Comment by mattcui** [comment]
@sykesm, Thanks for your suggestion. Seems there can't specify output binary path/name in [gexec.BuildIn](https://github.com/onsi/gomega/blob/master/gexec/build.go#L39), but there hardcoded "out/cpi" in our code, so it's not easy to use this pattern in the current situation, we will consider it later. Thanks.

**Comment by mattcui** [comment]
@sykesm, Thanks for your suggestion. Seems there can't specify output binary path/name in [gexec.BuildIn](https://github.com/onsi/gomega/blob/master/gexec/build.go#L39), but there hardcoded "out/cpi" in our code, so it's not easy to use this pattern in the current situation, we will consider it later. Thanks.
