### ISSUE TITLE
Information in dev/README.md appears stale, incorrect, or incomplete

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#116]
The information under the [Normal Testing](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/dev/README.md#normal-testing) heading doesn't seem right.

First, the link to the bosh-softlayer-cpi-release doesn't work. That appears to be due to the recent project move. Ignoring that, I can't find a `Vagrantfile` or any other instructions or information in the release on testing.

Updating the documentation to more clearly explain test approaches would help those of us that are trying to use or contribute to the project.

**Comment by maximilien** [comment]
Hey, @sykesm, thanks for feedback. We added a bug [#120648861](https://www.pivotaltracker.com/story/show/120648861) in the tracker for address this.

**Comment by maximilien** [comment]
Also @cunnie and I submitted [PR 149](https://github.com/cloudfoundry/docs-bosh/pull/149) on `bosh-docs` which will contain (eventually) all authoritative docs to get started.

/cc @mattcui and @jianqiu

**Comment by gu-bin** [comment]
@sykesm https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/dev/README.md has been updated.
