### ISSUE TITLE
Is the 'OS_RELOAD_ENABLED' environment variable still used?

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#120]
It appears all integration tests and the softlayer_creator unit test explicitly set the OS_RELOAD_ENABLED environment variable to TRUE. I'm trying to understand why that's being set as I can find no production code that references it in this release or its dependencies.

If the code is unused, it should be removed as it makes it harder to reason about what's going on in the code.

(Moved here from https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/issues/26)

**Comment by maximilien** [comment]
So this was added early during development as we were investigating `os_reload` feature. Perhaps @mattcui can help answer where this is now?

**Comment by mattcui** [comment]
Yes, this logic has never been tested, and no one ever used it. It would make code look complicated and ugly, I agree to remove this functionality. I will open a tracker.

**Comment by maximilien** [comment]
@mattcui closing this based on tracker issue. Please add a reference to keep things connected.
