### ISSUE TITLE
util/ssh_client.go is untested

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#121]
While attempting to update the ssh client code to support upload from a reader instead of a file, I discovered that `util.sshClientImpl` is untested code.  The unit test file simply creates a fake, drives methods against it, and then uses the fake to get the arguments that were passed to it.

To be clear: *no production code* is exercised by the tests. I replaced the production code with the following and all unit tests passed without modification:

```go
package util

import bscutilfakes "github.com/cloudfoundry/bosh-softlayer-cpi/util/fakes"

type SshClient interface {
	ExecCommand(username string, password string, ip string, command string) (string, error)
	UploadFile(username string, password string, ip string, srcFile string, destFile string) error
	DownloadFile(username string, password string, ip string, srcFile string, destFile string) error
}

type sshClientImpl struct{}

func GetSshClient() SshClient {
	return &bscutilfakes.FakeSshClient{}
}
```

**Comment by maximilien** [comment]
This will be addressed
