### ISSUE TITLE
Persistent disk allocation is flakey

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#132]
When deploying a job with a persistent volume, the deployment fails with the following:

```
Creating disk of size '1024': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 9294521 (00:05:19)
```

The task log on the director only contains the following:

```
D, [2016-06-22 17:11:21 #24756] [canary_update(consul_z1/0 (99dcc2f0-648f-41cb-8976-953326dd42b0))] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"create_disk","arguments":[1024,{},"21699145"],"context":{"director_uuid":"9489a253-16f8-4dd4-b2d0-d7ac38a646b7"}} with command: /var/vcap/jobs/softlayer_cpi/bin/cpi
...
D, [2016-06-22 17:16:35 #24756] [canary_update(consul_z1/0 (99dcc2f0-648f-41cb-8976-953326dd42b0))] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Creating disk of size '1024': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 9294521","ok_to_retry":false},"log":""}, err: , exit_status: pid 25280 exit 0
E, [2016-06-22 17:16:35 #24756] [canary_update(consul_z1/0 (99dcc2f0-648f-41cb-8976-953326dd42b0))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Clouds::CloudError: Creating disk of size '1024': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 9294521>
```

When I go to the softlayer portal, I see the disk has been created. When I go to the orders, I see my order was approved and I was charged for the allocation. I don't know if this is a timing issue or something else as there's no data in the logs - but it does get expensive after a while.

**Comment by jianqiu** [comment]
@sykesm 
When ordering persistent disk on SL, CPI firstly placed the order, that was why you saw "order id 9294521" in the log, then CPI would introduce polling of the status of provisioning disk, it throwed the error if it could not get the disk_id after 5 minute.
I also encountered this problem yesterday, I guess SL was not in a good situation. I will increase the polling time to mitigate this kind of problem.

**Comment by lehoanganh** [comment]
same by myself. We were facing multiple times with this issue e.g.

```
Failed updating job whisk-core: whisk-core/0 (canary) (00:05:36): Creating disk of size '512000': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id XXXXXXX
```

**Comment by Freyert** [comment]
I'm fairly new to the SL portal, is there a way we could view these order IDs to see how long it took them to fulfill? It might give us a better idea for how long to set the time out.

**Comment by mattcui** [comment]
@Freyert eCPI v2.0.0 extended the timeout from 5 mins to 10 mins. In addition, we also have PRs for addressing the customization for this timeout value. It will be supported when [PR 164](https://github.com/cloudfoundry/bosh-softlayer-cpi/pull/164) is merged. But keep in mind that it will only be supported by eCPI v2 release.

**Comment by Freyert** [comment]
@mattcui it looks like you're setting a bunch of environment variables. Does that mean that if I were to set those environment variables now this would work? And then after the PR is merged I could specify those values in the manifest?

**Comment by mattcui** [comment]
@Freyert Need to specify in CPI configuration file (cpi.json), something like this:

```
      "softlayer": {
        "username": <api_user>,
        "apiKey": <api_key>,
        "featureOptions":{
          "apiWaitTime":3,
          "apiRetryCount":5,
          "createIscsiVolumeTimeout":600,
          "CreateISCSIVolumePollingInterval":20
        }
      },
```

**Comment by Freyert** [comment]
@mattcui 

Also seeing this:

```
   Failed updating job slave > slave/2: Creating disk of size '20480': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 0 (00:06:10)
   Failed updating job slave > slave/0: Creating disk of size '20480': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 0 (00:06:12)
   Failed updating job slave > slave/1: Creating disk of size '20480': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 0 (00:06:13)
   Failed updating job slave (00:06:13)
   Failed updating job master > master/2: Creating disk of size '20480': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 0 (00:07:07)
   Failed updating job master > master/0: Creating disk of size '20480': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 0 (00:07:11)
```

Note: the order id is 0. That can't be right.

**Comment by mattcui** [comment]
@Freyert Could you please provide the corresponding cpi log? Especially for the return result of calling SL API to place the order (/placeOrder.json), thanks.

**Comment by Freyert** [comment]
```
[softlayer-go] Request:
PUT /rest/v3/SoftLayer_Network_Storage/15538729/allowAccessFromVirtualGuest.json HTTP/1.1^M
Host: api.softlayer.com^M
^M
{"parameters":[{"accountId":432060,"createDate":"2016-10-25T07:43:14-06:00","dedicatedAccountHostOnlyFlag":true,"domain":"softlayer.com","fullyQualifiedDomainName":"*****","hostname":"******","id":25147873,"maxCpu":4,"maxCpuUnits":"CORE","maxMemory":8192,"modifyDate":"2016-10-25T07:51:31-06:00","startCpus":4,"statusId":1001,"uuid":"*******","globalIdentifier":"******","primaryBackendIpAddress":"******","primaryIpAddress":"******","location":{"id":575240,"longName":"","name":"23"},"datacenter":{"id":449494,"longName":"Dallas 9","name":"dal09"},"networkComponents":[{"maxSpeed":1000},{"maxSpeed":1000}],"operatingSystem":{"passwords":[{"username":"********","password":"******"}]}}]}
[softlayer-go] Response:
HTTP/1.1 500 Internal Server Error^M
Connection: close^M
Content-Length: 277^M
Content-Type: application/json^M
Date: Tue, 25 Oct 2016 13:58:18 GMT^M
Server: Apache^M
Vary: Accept-Encoding^M
X-Frame-Options: SAMEORIGIN^M
^M
{"error":"A Volume Provisioning is currently in progress on volume IBM01SL432060-472. During this process, the requested operation (Host Authorization) cannot be completed until the process is finished.","code":"SoftLayer_Exception_Network_Storage_BlockingOperationInProgress"}
```

**Comment by mattcui** [comment]
@Freyert Is there any log around /placeOrder.json?

**Comment by Freyert** [comment]
It seems that what's happening is that when you order a disk, but BOSH times out; the disk is eventually created by SoftLayer. After enough deployments like this SoftLayer fills up and you get id 0 whenever you try to order.

**Comment by mattcui** [comment]
@Freyert I think [PR 164](https://github.com/cloudfoundry/bosh-softlayer-cpi/pull/164) can mitigate this pain especially when SL responds slower

**Comment by Freyert** [comment]
Ah thanks @mattcui. So that lets you set the time out length from the director? Or is it from the deployment manifest as well?

I feel like the more important problem to remedy is the fact that the CPI is not storing the order ID for the disk with the VMs. The ideal behavior would be for this scenario to occur:

1. CPI tries to order disks, but the time out occurs and the deployment fails.
2. The CPI stores the disk order ID
3. Several minutes pass and I `bosh deploy --recreate`
4. CPI finds the info in its DB from the previous deployment.
5. Finds that the drives have been created on Softlayer.
6. Finishes deployment.

**Comment by vvraskin** [comment]
I've got a similar issue, the disk cannot be attached to the vm since the order id `0` is not found. 

```
[2016-11-11 10:24:18 #22148] [canary_update(database_lon02/1)] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Creating disk of size '81920': Create SoftLayer iSCSI disk error.: Cannot find an performance storage (iSCSI volume) with order id 0","ok_to_retry":false},"log":""}, err: , exit_status: pid 23470 exit 0
```

**Comment by Freyert** [comment]
@vvraskin typically an Order ID of 0 means that Softlayer has returned an error when trying to order the disk. The issue I've typically that you've run into is that we've exceeded the number of disks allowed for our account.

**Comment by maximilien** [comment]
Have you all used the latest release of CPI for this? I don't believe we are seeing this and could be the quota issue @Freyert is mentioning. 

Closing this as done and @vvraskin please reopen if you feel it's still a thing.
