### ISSUE TITLE
SSH connections are leaked during polling

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#143]
[`ExecCommand`](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/util/ssh_client.go#L33) fails to close the ssh client and leaks a connection for every command that is executed. During a failed deployment, the CPI eventually exhausted its file descriptors on the bosh director.

**Comment by mattcui** [comment]
Sorry, there missed `defer client.Close()` right after [`ExecCommand`](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/util/ssh_client.go#L33) , we will make sure to fix it in eCPI v2 release.

**Comment by mattcui** [comment]
Fixed in the commit -> https://github.com/cloudfoundry/bosh-softlayer-cpi/commit/24b38f0b867ca292b36f8b23d2081d14f8381553

Closing this issue now.
