### ISSUE TITLE
Errors from the SoftLayer CPI need to be propagated to the bosh task log

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi#146]
During a deployment, the CPI tried to create a virtual guest. The request to the SL API failed with a 500 and the following response body:

``` json
{
   "error" : "There are insufficient resources behind router bcr04a.dal09 to fulfill the request for the following guests: diego-furnace-compilation-20160720-014141-450",
   "code" : "SoftLayer_Exception_Public"
}
```

The CPI then turned that into the following bosh error:

``` json
{
   "result" : null,
   "error" : {
      "message" : "Creating VM with agent ID '8812add0-5f04-4d03-8c90-8061e3215ce5': Creating VirtualGuest from SoftLayer client: softlayer-go: could not SoftLayer_Virtual_Guest#createObject, HTTP error code: '500'",
      "type" : "Bosh::Clouds::CloudError",
      "ok_to_retry" : false
   },
   "log" : ""
}
```

As you can see, all of the meaningful information from the error has been stripped. Debugging this issue requires direct access to the director VM and the CPI logs.

**Comment by mattcui** [comment]
I ever raised the similar [issue 101](https://github.com/maximilien/softlayer-go/issues/101) for [softlayer-go](https://github.com/maximilien/softlayer-go), we will improve it.

**Comment by maximilien** [comment]
`softlayer-go` was updated so any release of CPI after should have this fixed.

Closing.
