### ISSUE TITLE
has_vm should return false when vm cannot be found

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-softlayer-cpi#149]
has_vm seems to return an error instead of a boolean response when vm is not found:

```
Started scanning 4 vms > Checking VM states. Failed: Finding VM '22807707': Failed to find VM or Baremetal 22807707 (00:00:41)
```

above makes cck unusable unfortunately.

See https://bosh.io/docs/cpi-api-v1.html#has-vm for more details. I would also check if has_disk has proper behavior.

cc @mattcui @jfmyers9

**Comment by mattcui** [comment]
@cppforlife I think we followed the [has_vm sample](https://github.com/cppforlife/bosh-warden-cpi-release/blob/master/src/github.com/cppforlife/bosh-warden-cpi/action/has_vm.go#L20) to write our [has_vm code](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/action/has_vm.go#L21), isn't it correct? Thanks.

**Comment by mattcui** [comment]
@cppforlife @jfmyers9 @maximilien I confirmed with @jianqiu that we already fixed the issue a week ago, and the change has been in the latest eCPI release [2.3.18](https://bosh.io/releases/github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release?version=2.3.18) on bosh.io.

**Comment by maximilien** [comment]
@mattcui thanks. Closing this and will look forward to accepting story in tracker.
