### ISSUE TITLE
A proposal to protect the data on the persistent disk.

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi#156]
I would like to raise this issue to discuss about the problem where the persistent disks were re-partitioned and formatted accidentally/mistakenly by bosh-agent. It's hard to find the root cause since we didn't find a way to recreate the problem. Basically, it seemed that there had something wrong with disk host or network which resulted in a "bad" situation of the persistent disk, bosh-agent mistakenly assumed the disk was not partitioned, and tried to partition and format. It's a very serious problem, we need to come up with a solution or workaround to protect the data on the persistent disk, especially the disk must not be partitioned during stemcell update. We can leverage `UsePreformattedPersistentDisk` to protect the data, but we need a way to enable or disable this option to handle different situation (creating or a new VM or OS reloading an existing VM) properly. I have a proposal to have CPI smart enough to handle it:
1. When creating a new VM, need to make sure `UsePreformattedPersistentDisk` is set false in agent.json before attaching the disk, so that the bosh-agent is able to partition and format the persistent disk. CPI needs a new function to detect if the disk is mounted and enable `UsePreformattedPersistentDisk` right after it's mounted.
2. When OS reloading an existing VM, just need to set true to `UsePreformattedPersistentDisk` in `agent.json` before attaching the disk (disk discovery and session login).

@jianqiu @maximilien it's an emergency issue, we need a solution and implement it it in next 1 or 2 days. any thoughts to my proposal? Thanks.
@cppforlife Your comments are always welcome. Thanks.

**Comment by mattcui** [comment]
The advantage of this proposal is that it just needs changes from CPI side, no need to change stemcell or bosh-agent, the side effect is there still needs to SSH login from CPI to the target VMs, so this is a short-term solution, which could help us protect the data before we figure out a better solution (may be from bosh-agent side).

/cc @jianqiu @maximilien @cppforlife

**Comment by maximilien** [comment]
@mattcui did you keep all logs from that VM. Can you share (not necessarily here) but secure them and share with me and @cppforlife and Beijing team. Thanks.

**Comment by Freyert** [comment]
What about eVault? It would be pretty hand to be able to set up eVault on servers you find especially critical.

**Comment by mattcui** [comment]
@Freyert I don't know much about eVault, any detailed info?

**Comment by Freyert** [comment]
@mattcui well, eVault is a pretty strong back up solution that constantly backs up drives in the background.

It might be a good first step just to allow users to:

1. allocate snapshot space.
2. set a snapshot schedule for the drive.

**Comment by mattcui** [comment]
@Freyert The proposal I raised in this issue is intended to not go through disk partition code if the disk is already partitioned and formatted, it think backup is a different topic we could discuss in another thread. Thanks.

**Comment by Freyert** [comment]
So I've played with eVault a little bit, and it's not the way to go.

SoftLayer Endurance storage provides mechanisms by which you can schedule snapshots. The middle of the road allows for 4 IOPS/GB which should be sufficient for most use cases.

Providing a _backwards_ compatible field in the deployment manifest to specify endurance disk ordering should be a sufficient mechanism to smoothly allow teams to migrate to the new disk type.

**Comment by maximilien** [comment]
So for endurance storage while you can snapshot it appears that it also creates some limitations. Reading from [this blog post](http://blog.softlayer.com/tag/storage) from SL:

```
Endurance is available in three IOPS performance tiers to support varying application needs. Note: Once provisioned, you cannot migrate between tiers.

* 00.25 IOPS per GB: Designed for workloads with low I/O intensity. These workloads are typically characterized by having a large percentage of data inactive at a given time. Example applications include storing mailboxes or departmental level file shares.
* 2 IOPS per GB: Designed for most general purpose usage. Example applications include hosting small databases backing web applications or virtual machine disk images for a hypervisor.
* 4 IOPS per GB: Designed for higher-intensity workloads. These workloads are typically characterized by having a high percentage of data active at a given time. Example applications include transactional and other performance-sensitive databases.
```
Is that good enough for you?

**Comment by Freyert** [comment]
@maximilien yes those would be fine. I think the 4 IOPS should do quite well.

**Comment by maximilien** [comment]
I believe this is possible now. Please try

**Comment by Freyert** [comment]
@maximilien I just looked through the code and I didn't really see that anything had changed with disks? Who implemented this? Where are the commits associated? Tests?

**Comment by maximilien** [comment]
@mattcui and @jianqiu see ^^^ and help answer @Freyert's question. Thx

**Comment by mattcui** [comment]
@Freyert the only change we made to improve this area is in [bosh-agent issue 92](https://github.com/cloudfoundry/bosh-agent/issues/92)

**Comment by Freyert** [comment]
I think the best course of action here would be to create a specific issue about supporting Endurance Storage, and snapshot scheduling.

**Comment by maximilien** [comment]
Sure, @Freyert, that works for me. Can you please include in there use-cases as well as SL APIs you would use to implement. I will then discuss with team and see what we can do for next version.

Ideally, of course, we would welcome a contribution since there are tons of other priorities and not clear this is one of them.
