### ISSUE TITLE
unable to execute set of command on bosh ssh vm machine (Automcation)

### ISSUE THREAD

**Issue by ishwar1987** [cloudfoundry/bosh-softlayer-cpi#169]
Hi,
I need to execute the some set of command on bosh vm. I use the following script.

bosh download manifest testjob > cf-testjob.yml
bosh deployment cf-testjob.yml
bosh ssh  testvm/0  < script.sh

script.sh contain the set of shell script command that need to be execute on testvm/0 machine.
But while execute this script its giving me following error:
Pseudo-terminal will not be allocated because stdin is not a terminal.

Any idea how to do or any alternate way?
Thanks in advance.

**Comment by mattcui** [comment]
@ishwar1987 I believe your question/issue should be raised against BOSH, not CPI.

**Comment by ishwar1987** [comment]
ok. Thanks.
