### ISSUE TITLE
Example bosh-init manifest is out of date.

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/bosh-softlayer-cpi#206]
When trying to stand up the bosh director, I was using [this manifest](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/docs/bosh-init-usage.md) as my template, but I noticed that the stemcells and release versions were out of date. What would be cool is if this file gets auto updated as part of the CI with all of the latest releases, stemcells and appropriate sha versions.

**Comment by mattcui** [comment]
@DanLavine do you a good sample to reference? Thanks.

**Comment by maximilien** [comment]
I believe @gu-bin has some that she can share and update bosh.io with.

**Comment by gu-bin** [comment]
Doc https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/docs/bosh-init-usage.md has been deleted via PR #202
