### ISSUE TITLE
Setting up softlayer infrastructure

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/bosh-softlayer-cpi#208]
When looking at the the [manifest in this page](https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/docs/bosh-init-usage.md), I noticed that I needed to replace the networkVlan IDs. Currently I am using a infrastructure that has already been setup for me and was able to figure out what was being requested. However, if there wasn't an infrastructure already provided for me, then I wouldn't know what needed to be provisioned, like number of IP address for a cf deployment. Is there any documentation on setting up the Softlayer infrastructure itself? For example, the [aws environment setup](http://docs.cloudfoundry.org/deploying/aws/setup_aws.html) goes through everything that is needed with pictures.

**Comment by mattcui** [comment]
@DanLavine  I think you might try to find some docs like this -> https://bosh.io/docs/init-softlayer.html

**Comment by maximilien** [comment]
Let's make sure everything is up to date. 

@gu-bin please take a look when back from CNY. Best,

max

**Comment by gu-bin** [comment]
Doc https://github.com/cloudfoundry/bosh-softlayer-cpi/blob/master/docs/bosh-init-usage.md has been deleted via PR #202
